### ISSUE TITLE
"Live" self-test mechanism

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#174]
We have a relengapi staging environment, but it's not always clear how to know that things in that environment are working properly.

The idea here is to create a test framework separate from the unit tests which runs against a "live" site (given its URL) in a separate process.  A kind of large-scale integration test.

I'd most like to use this to test the authentication and authorization functionality.  It would also be great to test the tree-closing bits of relengapi, such as clobberer.

The tricky bit will be figuring out a way to automate authentication, as we'll need a few accounts with different permissions to verify that some users can do X while others cannot.  My thought is to use the application secret to create passwords in the form of a JWT that specifies the user details.  So, for example, a user `__selftest_client_create` might have a password of `JWT({"selftest": true, "perms": ["client.create"]})`.  This self-test authentication would be enabled in staging and disabled in production.

**Comment by Callek** [comment]
One thing I was looking at the other day, which I felt quite interesting and might support this use-case is https://www.runscope.com/ -- I have NO idea how stable/useful it is, or if the cost is appropriate though.

Either way I like this idea, but I would purport it doesn't belong in this repo, since it will involve a lot of configuration/consumer specific implementation details.
